trustroots__fqdn: 'dev2.trustroots.org'  # TODO: make configurable

trustroots__user: 'trustroots'  # TODO: make configurable

trustroots__influxdb_database: 'trustroots'

trustroots__root_path: '/srv/www/sites/{{ trustroots__fqdn }}'
trustroots__current_root_path: '{{ trustroots__root_path }}/current'

# trustroots__git_repo: 'https://github.com/Trustroots/trustroots.git'
# trustroots__git_ref: 'production'  # TODO: make configurable

trustroots__keyring__dependent_apt_keys:
  # mongodb
  - id: 'E162F504A20CDF15827F718D4B7C549A058F8B6B'
    repo: 'deb https://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main'
    state: 'present'
  # influxdb
  - id: '05CE15085FC09D18E99EFB22684A14CF2582E0C5'
    repo: 'deb https://repos.influxdata.com/debian buster stable'
    state: 'present'

trustroots__packages:
  - 'mongodb-org'
  - 'graphicsmagick'
  - 'python3-influxdb' # for influxdb_* ansible modules
  - 'influxdb'
  #- 'build-essential' # only needed if we deploy via git

trustroots__pki_realms:
  - name: '{{ trustroots__fqdn }}'
    acme_default_subdomains: [ ]
    acme: True

trustroots__nginx__dependent_servers:
  - '{{ trustoots__nginx_server }}'

# for options see:
# https://docs.debops.org/en/master/ansible/roles/nginx/defaults-detailed.html#nginx-servers
trustoots__nginx_server:
  by_role: 'trustroots'
  enabled: True
  type: 'proxy'
  state: 'present'
  name: '{{ trustroots__fqdn }}'
  pki_realm: '{{ trustroots__fqdn }}'
  root: '{{ trustroots__current_root_path }}/public'
  webroot_create: False
  location:
    '/': |
      try_files $uri @trustroots;

    '@trustroots': |
      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port  443;
      proxy_pass http://unix:/run/trustroots-server.socket;