---
# pki_realms:
#   - name: 'dev2.trustroots.org'
#     acme: True
#     # acme_default_subdomains: []
#     # acme_domains: []


pki_realms:
  - name: '{{ ansible_fqdn }}'
    acme_default_subdomains: [ ]
    acme: True
    #acme_ca: 'le-staging'


# this should be created anyway... but for some reason...
# well, it created it, but it still had an acme/error.log damn I should have looked at the error
# but after I removed it and re-ran the command it was ok... but not so satifying.
# I think at this point I need to put it public and ask the people.
pki_create_acme_challenge_dir: True

# or maybe this is enough, but it should have been true anyway, but maybe we didn't load that in somehow...
# but still, this only sets the fact "ansible_local.nginx.acme" which we check at another point to see if
# the thing should be set...
#nginx_acme: True