---
#system_users__accounts:

# disables the "current ansible user" behaviour
# we want to specify users specifically
system_users__self: False

system_users__accounts:
  - name: 'nick'
    group: 'nick'
    shell: 'bash'
    admin: True
    sshkeys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOpgeDCFf/6VbioHB6Fe6MYFmw/gJqZG/orscecGtwtl Nick Sellen <hello@nicksellen.co.uk> 2019-12-01
    state: 'present'